
#数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/edu?useUnicode=true&characterEncode=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
#mybatis和mybatisplus
mybatis:
  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#  type-aliases-package: com.aaa.demo.model
# 服务器
server:
  port: 8888


# 日志
logging:
  level:
    com.aaa.todo.dao: debug
    com.aaa.todo.controller: debug